services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    service.request.processor:
        class: Garlic\Bus\Service\Processor\RequestProcessor
        public: true
        arguments:
            - "@service.request"
            - "@service.response"
            - "@router"
            - "@kernel"
            - "@logger"
        tags:
            - { name: 'enqueue.client.processor'}

    service.command.processor:
        class: Garlic\Bus\Service\Processor\CommandProcessor
        public: true
        arguments:
            - "@service.request"
            - "@service.response"
            - "@router"
            - "@kernel"
            - "@logger"
        tags:
            - { name: 'enqueue.client.processor'}

    service.event.processor:
        class: Garlic\Bus\Service\Processor\MulticastEventProcessor
        public: true
        arguments:
            - "@service.request"
            - "@service.response"
            - "@router"
            - "@kernel"
        tags:
            - { name: 'enqueue.client.processor', topicName: '%env(SERVICE_NAMESPACE)%.%env(MULTICAST_TOPIC_NAME)%'}

    service.request.producer:
        class: Garlic\Bus\Service\Producer\RequestProducer
        arguments:
            - "@enqueue.transport.context"
            - '@enqueue.transport.rpc_factory'
            - "@service.response"
            - "%env(SERVICE_NAME)%"
            - "%env(SERVICE_NAMESPACE)%"

    service.command.producer:
        class: Garlic\Bus\Service\Producer\CommandProducer
        arguments:
            - "@enqueue.transport.context"
            - '@enqueue.transport.rpc_factory'
            - "@service.response"
            - "%env(SERVICE_NAME)%"
            - "%env(SERVICE_NAMESPACE)%"

    service.event.producer:
        class: Garlic\Bus\Service\Producer\EventProducer
        arguments:
            - "@enqueue.transport.context"
            - '@enqueue.transport.rpc_factory'
            - "@service.response"
            - "%env(SERVICE_NAME)%"
            - "%env(SERVICE_NAMESPACE)%"

    service.request:
        class: Garlic\Bus\Service\Request\RequestService
        arguments:
            - "@jms_serializer.serializer"

    service.response:
        class: Garlic\Bus\Service\Request\ResponseService
        arguments:
            - "@jms_serializer.serializer"

    Garlic\Bus\Service\CommunicatorService:
        class: Garlic\Bus\Service\CommunicatorService
        public: true
        arguments:
            - "@service.event.producer"
            - "@service.request.producer"
            - "@service.command.producer"
            - '@Garlic\Bus\Service\Pool\QueryPoolService'
            - "@service.request"
            - "@request_stack"
            - "%env(SERVICE_NAMESPACE)%"

    communicator:
        alias: Garlic\Bus\Service\CommunicatorService
        public: true

    Garlic\Bus\Service\GraphQLService:
        class: Garlic\Bus\Service\GraphQLService
        public: true

    Garlic\Bus\Service\Pool\:
      resource: '../../Service/Pool/*'