parameters:
    parameter_namespace: '%env(SERVICE_NAMESPACE)%'
    parameter_name: '%env(SERVICE_NAME)%'
    parameter_topic: '%env(MULTICAST_TOPIC_NAME)%'
    env(REQUEST_TIMEOUT): 30000
    env(UPLOAD_DIR): '/var/www/public/upload/'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    service.request.processor:
        class: Garlic\Bus\Service\Processor\RequestProcessor
        public: true
        arguments:
            - "@service.request"
            - "@service.response"
            - "@router"
            - "@kernel"
            - "@logger"
        tags:
            - { name: 'enqueue.processor', topic: "%parameter_namespace%.%parameter_name%.request", client: 'bus' }

    service.command.processor:
        class: Garlic\Bus\Service\Processor\CommandProcessor
        public: true
        arguments:
            - "@service.request"
            - "@service.response"
            - "@router"
            - "@kernel"
            - "@logger"
        tags:
            - { name: 'enqueue.processor', topic: "%parameter_namespace%.%parameter_name%.command", client: 'bus' }

    service.event.processor:
        class: Garlic\Bus\Service\Processor\MulticastEventProcessor
        public: true
        arguments:
            - "@service.request"
            - "@service.response"
            - "@router"
            - "@kernel"
        tags:
            - { name: 'enqueue.processor', topic: "%parameter_namespace%.%parameter_topic%", client: 'bus' }

    service.request.producer:
        class: Garlic\Bus\Service\Producer\RequestProducer
        arguments:
            - '@Interop\Queue\Context'
            - '@Enqueue\Rpc\RpcFactory'
            - "@service.response"
            - "%env(SERVICE_NAME)%"
            - "%env(SERVICE_NAMESPACE)%"
            - "%env(REQUEST_TIMEOUT)%"

    service.command.producer:
        class: Garlic\Bus\Service\Producer\CommandProducer
        arguments:
            - '@Interop\Queue\Context'
            - '@Enqueue\Rpc\RpcFactory'
            - "@service.response"
            - "%env(SERVICE_NAME)%"
            - "%env(SERVICE_NAMESPACE)%"

    service.event.producer:
        class: Garlic\Bus\Service\Producer\EventProducer
        arguments:
            - '@Interop\Queue\Context'
            - '@Enqueue\Rpc\RpcFactory'
            - "@service.response"
            - "%env(SERVICE_NAME)%"
            - "%env(SERVICE_NAMESPACE)%"

    service.request:
        class: Garlic\Bus\Service\Request\RequestService
        arguments:
            - "@jms_serializer.serializer"

    service.response:
        class: Garlic\Bus\Service\Request\ResponseService
        arguments:
            - "@jms_serializer.serializer"

    Enqueue\Rpc\RpcFactory:
        class: Enqueue\Rpc\RpcFactory
        public: true

    Garlic\Bus\Service\CommunicatorService:
        class: Garlic\Bus\Service\CommunicatorService
        public: true
        arguments:
            - "@service.event.producer"
            - "@service.request.producer"
            - "@service.command.producer"
            - '@Garlic\Bus\Service\Pool\QueryPoolService'
            - "@service.request"
            - "@request_stack"
            - "%env(SERVICE_NAMESPACE)%"

    communicator:
        alias: Garlic\Bus\Service\CommunicatorService
        public: true

    Garlic\Bus\Service\Pool\:
        resource: '../../Service/Pool/*'

    Garlic\Bus\Service\File\FileHandlerService:
        public: true
        arguments:
            - "%env(HOST_URL)%"
            - "%env(UPLOAD_DIR)%"
    Garlic\Bus\Service\File\ScpFileUploadService:
        public: true
        arguments:
            - "%env(SCP_USERNAME)%"
            - "%env(SCP_PASSWORD)%"
            - "%env(UPLOAD_DIR)%"
