services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    service.request.processor:
        class: MessageBusBundle\Service\Processor\RequestProcessor
        arguments:
            - "@service.request"
            - "@service.response"
            - "@router"
        tags:
            - { name: 'enqueue.client.processor'}

    service.command.processor:
        class: MessageBusBundle\Service\Processor\CommandProcessor
        arguments:
            - "@service.request"
            - "@service.response"
            - "@router"
        tags:
            - { name: 'enqueue.client.processor'}

    service.request.producer:
        class: MessageBusBundle\Service\Producer\RequestProducer
        arguments:
            - "@enqueue.transport.context"
            - '@enqueue.transport.rpc_factory'
            - "@service.response"
            - "%env(SERVICE_NAME)%"
            - "%env(SERVICE_NAMESPACE)%"

    service.command.producer:
        class: MessageBusBundle\Service\Producer\CommandProducer
        arguments:
            - "@enqueue.transport.context"
            - '@enqueue.transport.rpc_factory'
            - "@service.response"
            - "%env(SERVICE_NAME)%"
            - "%env(SERVICE_NAMESPACE)%"

    service.request:
        class: MessageBusBundle\Service\Request\RequestService
        arguments:
            - "@jms_serializer.serializer"

    service.response:
        class: MessageBusBundle\Service\Request\ResponseService
        arguments:
            - "@jms_serializer.serializer"

    MessageBusBundle\Service\CommunicatorService:
        class: MessageBusBundle\Service\CommunicatorService
        public: true
        arguments:
            - "@service.request.producer"
            - "@service.command.producer"
            - "@service.request"
            - "@request_stack"
            - "%env(SERVICE_NAMESPACE)%"

    communicator:
        alias: MessageBusBundle\Service\CommunicatorService
        public: true